apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: microservice-namespace
  labels:
    app: api-service
spec:
  type: ClusterIP
  selector:
    app: api-service
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP