#Ideally should not be committed to the repository
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: microservice-namespace
type: Opaque
data:
  DATABASE_PASSWORD: cm9vdA== #base64 encoded 'root'
  POSTGRES_PASSWORD: cm9vdA== #base64 encoded 'root'
  POSTGRES_USER: cG9zdGdyZXM= #base64 encoded 'postgres'
