apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: microservice-namespace
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/postgresql/data